# Generated by Django 4.2.4 on 2023-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='current_user',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
